const mongoose = require("mongoose");

const serverConfigSchema = new mongoose.Schema({
    guildId: {
        type: String,
        required: true,
        unique: true,
    },
    channels: {
        type: Object,
        default: {
            welcome: "",
            report: "",
            modLog: "",
            memberLog: "",
            messageLog: "",
            voiceLog: "",
            ticket: [],
            level: "",
            restricted: [],
            blacklisted: [],
            minigame: [],
        },
    },
    moderation: {
        type: Object,
        default: {
            warnLimit: 3,
            timeoutDuration: 1000 * 60 * 60,
            modLogs: {
                warn: true,
                timeout: true,
                kick: true,
                ban: true,
            },
            memberLogs: {
                role: true,
                name: true,
                avatar: true,
            },
            messageLogs: {
                deleted: true,
                edited: true,
                purged: true,
            },
            voiceLogs: {
                join: true,
                move: true,
                leave: true,
            },
            blacklistedWords: [],
        },
    },
    level: {
        type: Object,
        default: {
            enabled: true,
            xpGainMin: 1,
            xpGainMax: 20,
            xpGainTime: 1000 * 60,
            xpBaseRequirement: 100,
            xpScaling: "multiply",
            ranks: [],
            multiplier: true,
            levelMessage: "{user} has leveled up to {level}",
            restricted: [],
        },
    },
    economy: {
        type: Object,
        default: {
            enabled: true,
            currency: "Karma coins",
            currencySymbol: "🪷",
            currencyGainMin: 5,
            currencyGainMax: 5,
            currencyGainTime: 1000 * 60,
            baseBalance: 100,
            dailyMin: 50,
            dailyMax: 100,
            coinflipReward: 100,
            minigameReward: 500,
            multiplier: true,
            multiplierBaseCost: 10000,
            multiplierIncrement: 0.2,
            multiplierCostScaling: "multiply",
            multiplierMax: 5,
            customRoles: true,
            customRoleCost: 20000,
            customRolePosition: "",
            customRoleLimit: 5,
            shopRoles: [],
            shopItems: [],
            groups: false,
            group: "Group",
            groupBaseCost: 10000,
            groupBaseUsers: 5,
            groupMultiplier: true,
            groupMultiplierBaseCost: 50000,
            groupMultiplierIncrement: 0.2,
            groupCostScaling: "multiply",
            groupCategory: "",
            groupRolePosition: "",
            restricted: [],
        },
    },
    commands: {
        type: Object,
        default: {
            disabled: [],
            blacklistedUsers: [],
            blacklistedUserCommands: [],
            blacklistedChannelCommands: [],
            cooldowns: [],
            defaultMinigameCooldown: 1000 * 60 * 3,
        },
    },
    data: {
        type: Object,
        default: {
            slotsTotal: 0,
            slotsCurrent: 0,
            totalSpent: 0,
            muted: [],
        },
    },
});

const model = mongoose.model("serverConfigs", serverConfigSchema);

module.exports = model;
